name: Push project to dockhost
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Project deploy
    runs-on: ubuntu-latest
    container:
      image: dockhost/cli
      env:
        DOCKHOST_TOKEN: ${{secrets.DOCKHOST_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push to dockhost
        run: dockhost compose apply -f dockhost.yaml
  restart-containers:
    name: Restart containers
    needs: deploy
    runs-on: ubuntu-latest
    container:
      image: dockhost.io/utils/cli:master
      env:
        DOCKHOST_TOKEN: ${{secrets.DOCKHOST_TOKEN}}
    steps:
      - name: Restart api
        run: dockhost container update-image --project titorelli-org --name api-service --image ghcr.io/titorelli-org/api-service
      - name: Restart models
        run: dockhost container update-image --project titorelli-org --name model-service --image ghcr.io/titorelli-org/model-service
      - name: Restart cas
        run: dockhost container update-image --project titorelli-org --name cas-service --image ghcr.io/titorelli-org/cas-service
      - name: Restart console
        run: dockhost container update-image --project titorelli-org --name console --image ghcr.io/titorelli-org/console
      - name: Restart text storage
        run: dockhost container update-image --project titorelli-org --name text-storage --image ghcr.io/titorelli-org/text-storage
