name: Push project to dockhost
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Project deploy
    runs-on: ubuntu-latest
    container:
      image: dockhost/cli
      env:
        DOCKHOST_TOKEN: ${{secrets.DOCKHOST_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push to dockhost
        run: dockhost compose apply -f dockhost.yaml
